 name: First Worflow
 on: push
 jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Demo Step
          run: echo "Wecloem to github actions"

        - name: Checkout Repo
          uses: actions/checkout@v5

        - name: list files
          run: ls
         
        - name: Print Readme
          run: cat README.md



