name: lions-workflow
on: push

jobs:
    job_1:
        runs-on: ubuntu-latest
        steps:
        - name: install cowsay
          run: sudo apt-get install cowsay -y

        - name: create dragon
          run: cowsay -f dragon "I am breathing fire" >> dragon.txt

        - name: Upload artifact
          uses: actions/upload-artifact@v4
          with: 
             name: dragon-file
             path: dragon.txt

    job_2:
        needs: job_1
        runs-on: ubuntu-latest
        steps:
            - name: wait for 10S
              run: sleep 10

            - name: download artifact
              uses: actions/download-artifact@v5
              with:
                name: dragon-file
                
            - name: check if dragon has arrived
              run: grep -i "fire" dragon.txt

    job_3:
        needs: [job_2]
        runs-on: ubuntu-latest
        steps:
            - name: Call dragon
              run: cat dragon.txt


