name: Second Workflow
on: push
 jobs:
    second-job:
        run-on: ubuntu-latest
        steps:
            - name: readme steps
            run: echo "this is the 2nd steps"
            
